import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
public static void main (String[] args) {
int t= Integer.parseInt(args[0]);
int seed = Integer.parseInt(args[1]);
Random generator = new Random(seed); 
 int n4=0, n2=0,n3=0, sum=0,kids=0;
 boolean ifboy=false;
 boolean ifgirl=false;
 double rnd=0.0;
 
 

 for( int i=0; i<t; i++)
 {
	while ((ifboy==false)||(ifgirl==false))
 {
 	rnd = generator.nextDouble();
 	if (a<0.5)
 	{
 		ifboy=true;
 	}
 	else
 	{
 		ifgirl=true;
 	}
 		
 	sum++;
 	kids++;
 }
 
 if (kids==2)
 {
 	n2++;
 }
 else
 {
 	if (kids==3)
 	{
 		n3++;
 	}
 	else
 	{
 		n4++;
 	}
 }
 ifboy=false;
 ifgirl=false;
 kids=0;

 }
 System.out.println("Average: "+((double)sum/t)+" children to get at least one of each gender.");
 System.out.println("Number of families with 2 children: "+n2);
 System.out.println("Number of families with 3 children: "+n3);
 System.out.println("Number of families with 4 children: "+n4);

		


		    
	}
}
